import Link from "next/link";
import "./globals.css";
import Header from "./Header/page";

export const metadata = {
  title: "LinkedX",
  description: "Generated by create next app",
};

export default function Layout({children}) {
  return (
    <html lang="en">
      <body>
        <nav className='nav-bar'>
          <Link className='links' href='/AllContacts'>All Contacts</Link>
          <Link className='links' href='/SearchContacts'>Search Contacts</Link>
          <Link className='links' href='/AddContacts'>Add Contacts</Link>
        </nav>

        {children}        

      </body>
    </html>
  );
}
